library(survival)
library(survminer)
library(ggplot2)
library(ggpubr)
library(magrittr)
library(dplyr)
library(svglite)

gene = 'COL4A1'
PFS_data = read.table('cohort 4.txt')
res.cut <- surv_cutpoint(PFS_data, time="Time_to_event", event="overall_survival_Event", variables = c(gene))
summary(res.cut)
plot(res.cut, gene, palette = "npg")
res.cat <- surv_categorize(res.cut)
fit <- survfit(Surv(Time_to_event, overall_survival_Event) ~COL4A1, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = FALSE, conf.int = FALSE, pval=TRUE, palette = c("#3b5181", "#19977f"))
ggsurvplot(fit, data = res.cat, risk.table = FALSE, conf.int = FALSE, pval=FALSE, palette = c("#3b5181", "#19977f"))
ggsave(filename='COL4A1_PFS.svg')
surv_pvalue(fit, method = "survdiff")
